export const actions = {
    profile: {
        "DATA_FETCHING": "PROFILE_DATA_FETCHING",
        "DATA_FETCHED": "PROFILE_DATA_FETCHED",
        "DATA_FETCH_ERROR": "PROFILE_DATA_FETCH_ERROR",
        "USER_DATA_EDITING": "PROFILE_USER_DATA_EDITING",
        "IMAGE_UPDATED": "PROFILE_IMAGE_UPDATED"
    },
    post: {
        "DATA_FETCHING": "POST_DATA_FETCHING",
        "DATA_FETCHED": "POST_DATA_FETCHED",
        "DATA_FETCH_ERROR": "POST_DATA_FETCH_ERROR",
        "DATA_CREATED": "POST_CREATED",
        "DATA_EDITING": "POST_DATA_EDITING",
        "POST_DELETE": "POST_DATA_DELETE",
    }
};
